apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: schahid-app
  namespace: argocd

spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/chahid001/IoT-schahid.git
    targetRevision: develop
    path: manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true