- name: Waiting for ArgoCD POD 
  command: kubectl wait --for=condition=Ready pod -l app.kubernetes.io/name=argocd-server -n argocd --timeout=5m

- name: Get ArgoCD password
  shell: kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
  register: argocd_pass

- name: Display ArgoCD Password
  debug: 
    var: argocd_pass.stdout